on:
  push:
    branches: ["main"]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: echo "hello world"
        run: echo "hello world"
      - name: update packages
        run: apt update 
      - name: install apache
        run: apt install apache2 -y
      - name: bye
        echo: "byeeeeeeeeeeeee"

