on:
  push:
    branches: ["main"]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        run: echo "hello world"
      - name: update packages
        run: sudo apt update 
      - name: install apache
        run: sudo apt install apache2 -y
      - name: bye
        run: echo "byeeeeeeeeeeeee"
    second:
      runs-on: ubuntu-latest
      steps:
        - name: second
          run: echo "hello world from second job, first job is completed"


